name: nadeem_electronics_app
description: Android WebView app for the live Nadeem Electronics website.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  connectivity_plus: ^6.1.2
  dio: ^5.7.0
  file_saver: ^0.3.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
